# Generated by Django 4.1.4 on 2022-12-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatement',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.customer'),
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.customer'),
        ),
        migrations.AddField(
            model_name='accountinformation',
            name='holder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountinformation', to='users.customer'),
        ),
    ]
