# Generated by Django 4.1.3 on 2022-11-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
    ]
