# Generated by Django 4.1.3 on 2022-11-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
