# Generated by Django 4.1.3 on 2022-11-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountinformation_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatement',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
