# Generated by Django 4.1.3 on 2022-11-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accountinformation_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinformation',
            name='account_number',
            field=models.CharField(default='HH60E6AA545C8', max_length=15, unique=True),
        ),
    ]
