# Generated by Django 4.1.3 on 2022-11-27 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_accountinformation_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatement',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='accountinformation',
            name='account_number',
            field=models.CharField(default='374HG9H1DA8HG', max_length=15, unique=True),
        ),
    ]
