# Generated by Django 4.1.3 on 2022-11-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_accountstatement_guid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinformation',
            name='balance',
        ),
        migrations.AlterField(
            model_name='accountinformation',
            name='account_number',
            field=models.CharField(default='CH5F13136G202', max_length=15, unique=True),
        ),
    ]
