# Generated by Django 4.1.3 on 2022-11-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_accountinformation_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinformation',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='accountinformation',
            name='account_number',
            field=models.CharField(default='6AD3AF1G8E7C4', max_length=15, unique=True),
        ),
    ]
