# Generated by Django 4.1.3 on 2022-11-28 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_accountinformation_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinformation',
            name='account_number',
            field=models.CharField(default='57HD836B5B870', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='accountstatement',
            name='banking_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountinformation'),
        ),
    ]
