# Generated by Django 4.1.3 on 2022-11-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_accountinformation_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinformation',
            name='account_number',
            field=models.CharField(default='H4GAAEA30B18H', max_length=15, unique=True),
        ),
    ]
