# Generated by Django 4.1.4 on 2022-12-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_accountinformation_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinformation',
            name='account_number',
            field=models.CharField(default='4E655H8571B6E', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='accountinformation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
