# Generated by Django 4.1.4 on 2022-12-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_accountinformation_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinformation',
            name='account_number',
            field=models.CharField(default='EBCGGEE45E3HD', max_length=15, unique=True),
        ),
    ]
