# Generated by Django 4.1.4 on 2022-12-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_accountinformation_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinformation',
            name='account_number',
            field=models.CharField(default='60C436AB8F766', max_length=15, unique=True),
        ),
    ]
